server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend.demo.svc.cluster.local:3000/api/;
  }

  location = /health {
    proxy_pass http://backend.demo.svc.cluster.local:3000/health;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
